--------------------------------------------------------
--  DDL for Table BSE_LOOKUP
--------------------------------------------------------

  CREATE TABLE "INVESTASISAA"."BSE_LOOKUP" 
   (	"LOOKUP_ID" NUMBER NOT NULL, 
	"LOOKUP_CODE" VARCHAR2(100 BYTE) NOT NULL, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"FLAG_ACTIVE" NUMBER(1,0), 
	"FLAG_SYSTEM" NUMBER(1,0), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(20 BYTE), 
	"LAST_UPDATE_DATE" DATE,
  CONSTRAINT BSE_LOOKUP_PK PRIMARY KEY(LOOKUP_ID)
   );
   
--------------------------------------------------------
--  DDL for Sequence BSE_LOOKUP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INVESTASISAA"."BSE_LOOKUP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Trigger BSE_LOOKUP_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INVESTASISAA"."BSE_LOOKUP_TRG" 
BEFORE INSERT ON BSE_LOOKUP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "INVESTASISAA"."BSE_LOOKUP_TRG" ENABLE;



--------------------------------------------------------
--  DDL for Table BSE_LOOKUP_ITEM
--------------------------------------------------------

  CREATE TABLE "INVESTASISAA"."BSE_LOOKUP_ITEM" 
   (	"LOOKUP_ITEM_ID" NUMBER NOT NULL, 
	"LOOKUP_ID" NUMBER NOT NULL, 
	"LOOKUP_ITEM_CODE" VARCHAR2(100 BYTE) NOT NULL, 
	"LOOKUP_ITEM_NAME" VARCHAR2(200 BYTE) NOT NULL, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(20 BYTE), 
	"LAST_UPDATE_DATE" DATE,
  CONSTRAINT BSE_LOOKUP_ITEM_PK PRIMARY KEY(LOOKUP_ITEM_ID),
  CONSTRAINT "BSE_LOOKUP_ITEM_FK1" FOREIGN KEY ("LOOKUP_ID")
	  REFERENCES "INVESTASISAA"."BSE_LOOKUP" ("LOOKUP_ID")
   ) ;

--------------------------------------------------------
--  DDL for Sequence BSE_LOOKUP_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INVESTASISAA"."BSE_LOOKUP_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Trigger BSE_LOOKUP_ITEM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INVESTASISAA"."BSE_LOOKUP_ITEM_TRG" 
BEFORE INSERT ON BSE_LOOKUP_ITEM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LOOKUP_ITEM_ID IS NULL THEN
      SELECT BSE_LOOKUP_ITEM_SEQ.NEXTVAL INTO :NEW.LOOKUP_ITEM_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "INVESTASISAA"."BSE_LOOKUP_ITEM_TRG" ENABLE;




--------------------------------------------------------
--  DDL for Table BSE_PARAMETER
--------------------------------------------------------

  CREATE TABLE "INVESTASISAA"."BSE_PARAMETER" 
   (	"PARAMETER_ID" NUMBER NOT NULL, 
	"PARAMETER_CODE" VARCHAR2(100 BYTE) NOT NULL, 
	"PARAMETER_VALUE" VARCHAR2(100 BYTE) NOT NULL, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"FLAG_ACTIVE" NUMBER(1,0), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE,
  CONSTRAINT BSE_PARAMETER_PK PRIMARY KEY(PARAMETER_ID)
   ) ;

--------------------------------------------------------
--  DDL for Sequence BSE_PARAMETER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INVESTASISAA"."BSE_PARAMETER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
  
--------------------------------------------------------
--  DDL for Trigger BSE_PARAMETER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INVESTASISAA"."BSE_PARAMETER_TRG" 
BEFORE INSERT ON BSE_PARAMETER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PARAMETER_ID IS NULL THEN
      SELECT BSE_PARAMETER_SEQ.NEXTVAL INTO :NEW.PARAMETER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "INVESTASISAA"."BSE_PARAMETER_TRG" ENABLE;
